build: 
  image: teaci/msys$$arch
  shell: mingw$$arch
  pull: true
  commands:
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-pkg-config mingw-w64-${target}-qt5
    - qmake -v
    - qmake "CONFIG+=release" EzGraver.pro
    - make
    - echo Mingw/:
    - ls -al /mingw$$arch/bin
    - echo C/Mingw:
    - ls -al C/msys$$arch/mingw$$arch/bin/
    - echo %PATH%
    - windeployqt.exe --release --no-translations EzGraverLib/release/EzGraverLib.dll
    - windeployqt.exe --release --no-translations EzGraverUi/release/EzGraverUi.exe
    - windeployqt.exe --release --no-translations EzGraverCli/release/EzGraverCli.exe
    
#before_deploy:
    
matrix:
  arch:
    - 64
    - 32
