build: 
  image: teaci/msys$$arch
  shell: mingw$$arch
  pull: true
  commands:
    # Compilation
    - export EZ_VERSION=$CI_TAG
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-pkg-config mingw-w64-${target}-qt5 zip
    - qmake -v
    - qmake -config release EzGraver.pro
    - make
    # Dependency collection
    # windeployqt searches for icu*.dll instead of libicu*.dll
    - mkdir dependencies
    - cp /mingw$$arch/bin/libicudt*.dll dependencies/
    - cp /mingw$$arch/bin/libicuin*.dll dependencies/
    - cp /mingw$$arch/bin/libicuuc*.dll dependencies/
    - for file in dependencies/lib* ; do mv "$file" "${file/lib/}" ; done
    - PATH=$PATH:$PWD/dependencies
    # Deployment
    - mkdir deploy
    - cp EzGraverCli/release/EzGraverCli.exe deploy/
    - cp EzGraverCore/release/EzGraverCore.dll deploy/
    - cp EzGraverUi/release/EzGraverUi.exe deploy/
    - windeployqt --release --no-translations --no-angle --no-opengl-sw deploy/EzGraverCli.exe
    - windeployqt --release --no-translations --no-angle --no-opengl-sw deploy/EzGraverCore.dll
    - windeployqt --release --no-translations --no-angle --no-opengl-sw deploy/EzGraverUi.exe
    # Add missing libraries. MSYS libs have to be added as well.
    # Generate final zip
    - if [ $$arch = 32 ]; then zip -r EzGraver_win_x86.zip deploy/; fi
    - if [ $$arch = 64 ]; then zip -r EzGraver_win_x64.zip deploy/; fi

#publish:
#  github_release:
#    api_key: $$GITHUB_RELEASES_TOKEN
#    files:
#      - EzGraver_win_x86.zip
#      - EzGraver_win_x64.zip
#    when:
#      event: tag

matrix:
  arch:
    - 64
    - 32
