build: 
  image: teaci/msys$$arch
  shell: mingw$$arch
  pull: true
  commands:
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-pkg-config mingw-w64-${target}-qt5
    - qmake -v
    - qmake "CONFIG+=release" EzGraver.pro
    - make
    
matrix:
  arch:
    - 64
    - 32
