environment:
  matrix:
    - arch: x86
      QT_DIR: C:\Qt\5.7\msvc2015_64
    - arch: x64
      QT_DIR: C:\Qt\5.7\msvc2015

install:
  - set PATH=%PATH%;%QT_DIR%\bin

before_build:
  - cd EzGraverCli & qmake -config release -tp vc -spec win32-msvc2015 EzGraverCli.pro & cd ..
  - cd EzGraverLib & qmake -config release -tp vc -spec win32-msvc2015 EzGraverLib.pro & cd ..
  - cd EzGraverUi & qmake -config release -tp vc -spec win32-msvc2015 EzGraverUi.pro & cd ..
  - qmake -config release -tp vc -spec win32-msvc2015 EzGraver.pro

configuration:
  - Release

after_build:
  - mkdir deploy
  - copy EzGraverCli\release\EzGraverCli.exe deploy\EzGraverCli.exe
  - copy EzGraverLib\release\EzGraverLib.dll deploy\EzGraverLib.dll
  - copy EzGraverUi\release\EzGraverUi.exe deploy\EzGraverUi.exe
  - windeployqt --release --no-translations --no-angle --no-opengl-sw deploy/EzGraverCli.exe
  - windeployqt --release --no-translations --no-angle --no-opengl-sw deploy/EzGraverLib.dll
  - windeployqt --release --no-translations --no-angle --no-opengl-sw deploy/EzGraverUi.exe
  - 7z a EzGraver_%arch%.zip .\deploy\*
  
deploy:
  provider: GitHub
  auth_token:
    secure: kQ5w9sYhOflgqli0RP05IzEMc946SuYcK7nyhsOivYd5MoC6QLgg9tknjt8ALkTn
  artifact: EzGraver_%arch%.zip
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
